apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gateway-cartagena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-gateway-cartagena
  template:
    metadata:
      labels:
        app: fastapi-gateway-cartagena
    spec:
      containers:
      - name: fastapi-gateway
        image: fastapi_gateway_cartagena:latest
        env:
        - name: POSTGREST_URL
          value: "http://postgrest-cartagena:3000"
        - name: HAPI_FHIR_URL
          value: "http://hapi-fhir-cartagena:8080/fhir"
        - name: JWT_SECRET
          value: "supersecretkey"
        - name: SEDES_URLS
          value: "http://cartagena.fastapi:8000,http://sincelejo.fastapi:8000,http://monteria.fastapi:8000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-gateway-cartagena
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fastapi-gateway-cartagena
