apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-citus-cartagena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-citus-cartagena
  template:
    metadata:
      labels:
        app: postgres-citus-cartagena
    spec:
      containers:
      - name: postgres
        image: citusdata/citus:11.2
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "adminpass"
        - name: POSTGRES_DB
          value: "hce_cartagena"
        ports:
          - containerPort: 5433 # Cartagena
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-citus-cartagena
spec:
  type: ClusterIP
  ports:
      - port: 5433
        targetPort: 5433
  selector:
    app: postgres-citus-cartagena
