apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-citus-sincelejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-citus-sincelejo
  template:
    metadata:
      labels:
        app: postgres-citus-sincelejo
    spec:
      containers:
      - name: postgres
        image: citusdata/citus:11.2
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "adminpass"
        - name: POSTGRES_DB
          value: "hce_sincelejo"
        ports:
        - containerPort: 5434 # Sincelejo
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-sincelejo
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-citus-sincelejo
spec:
  type: ClusterIP
  ports:
    - port: 5434
      targetPort: 5434
  selector:
    app: postgres-citus-sincelejo
